# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfApp', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('userAccount', models.CharField(max_length=20)),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
